# ==== RTSP ====
RTSP_USERNAME=${RTSP_USERNAME}
RTSP_PASSWORD=${RTSP_PASSWORD}
RTSP_PORT=${RTSP_PORT}
RTSP_PATH=${RTSP_PATH}

# ==== READ DB (cctv_read; 172.30.29.236) ====
spring.datasource.read.driver-class-name=${READ_DB_DRIVER_CLASS_NAME}
spring.datasource.read.jdbc-url=${READ_DB_URL}
spring.datasource.read.username=${READ_DB_USERNAME}
spring.datasource.read.password=${READ_DB_PASSWORD}

# ==== METRICS DB (health_metrics; 172.30.29.237) ====
spring.datasource.metrics.driver-class-name=${METRICS_DB_DRIVER_CLASS_NAME}
spring.datasource.metrics.jdbc-url=${METRICS_DB_URL}
spring.datasource.metrics.username=${METRICS_DB_USERNAME}
spring.datasource.metrics.password=${METRICS_DB_PASSWORD}


